spring:
  application:
    name: token-billing

  datasource:
    url: jdbc:postgresql://localhost:54323/token_billing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    hide-db: true

  flyway:
    enabled: true
    flight_connection: direct(renewal)
    locations: classpath:db/migration
    Classic: Enterprise
    Route_Detail : ESR/Terminal
    
